### ISSUE TITLE
'foo.lenght' typo in setting functions not a problem?

### ISSUE THREAD

**Issue by vincent0794** [ntableman/Balboa-Spa-HomeKit#6]
Hi - please bear with my mild confusion as I continue to grep how node-red fully works.

I'm surprised to see in all the function node (turn on light, turn on pump1, etc), code like this:

var buf = Buffer.alloc(9,"hex");

var message = 0x0a;
var foo = buf.fill(message,2,3);
message = 0xbf;
foo = buf.fill(message,3,4);
message = 0x11;
foo = buf.fill(message,4,5);
message = 0x11;
foo = buf.fill(message,5,6);
message = 0x00;
foo = buf.fill(message,6,7);

var len = foo.lenght+5;
...

Where there's a clear code typo (should be foo.length+5) on that last line. Yet somehow this doesn't seem to stop anything from working, and I'm not seeing any errors in any logs.

Can you clarify how this flow works and why the above isn't a problem please?

**Comment by ntableman** [comment]
no I cannot...except I have severe dyslexia.

**Comment by ntableman** [comment]
In case you didnt see it https://github.com/vincedarley/homebridge-plugin-bwaspa
